- name: Add .gitconfig
  become: yes
  template:
    src: templates/gitconfig.j2
    dest: "/home/{{ item }}/.gitconfig"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop: "{{ users_list }}"
