- hosts: webservers
  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html 
  tasks:
  
    - name: Install nginx
      apt: name=nginx state=present update_cache=yes
      become: yes
   
    - name: Copy index.html into nginx
      copy: src=files/index.html dest="{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes
    
    - name: Copy config filex into nginx
      template: src=files/nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
